### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by d0ubl3puls4r** [stormshadow07/HackTheWorld#2]
Hi, when I run HackTheWorkd.py I get the error message:

Traceback (most recent call last):
  File "./HackTheWorld.py", line 19, in <module>
    from termcolor import colored
ImportError: No module named termcolor

How can I solve this problem?

Thank you.

**Comment by stormshadow07** [comment]
**So For every Module Not found  in Python You can install Modules using pip**
**Eg:**
`pip install <module_name>`
**For your case Just Enter in the Terminal**
`pip install termcolor`

**If further  any Module is not found, just replace Module_name**

**Comment by d0ubl3puls4r** [comment]
Thank you, have solved the problem here.
