### ISSUE TITLE
Program cannot start

### ISSUE THREAD

**Issue by XemBryan** [stormshadow07/HackTheWorld#20]
On win10 I get error
kali@DESKTOP-F6695VT:~/HackTheWorld$ python HackTheWorld.py

> Traceback (most recent call last):
>   File "HackTheWorld.py", line 17, in <module>
>     from Crypto.Hash import MD5
> ImportError: No module named Crypto.Hash

On Kali VM
root@kali:~/HackTheWorld# sudo python HackTheWorld.py 

> Traceback (most recent call last):
>   File "HackTheWorld.py", line 19, in <module>
>     from termcolor import colored
> ImportError: No module named termcolor

**Comment by stormshadow07** [comment]
@XemBryan its a closed issue already.
Also, Script will work on Kali Linux not in Windows because of dependencies.
sudo pip install termcolor
