### ISSUE TITLE
ImportError: No module named termcolor

### ISSUE THREAD

**Issue by ghost** [stormshadow07/HackTheWorld#5]

**Comment by ivanvidalsepulveda** [comment]
python HackTheWorld.py
Traceback (most recent call last):
  File "HackTheWorld.py", line 19, in <module>
    from termcolor import colored
ImportError: No module named termcolor

i have same error

**Comment by TheGodM** [comment]
bro solution is simple try it in console
sudo pip install termcolor

**Comment by stormshadow07** [comment]
@theonegitHub Follow the @TheGodM command.

**Comment by kero1997** [comment]
pip install termcolor

**Comment by swarnava101** [comment]
> pip install termcolor

but its saying already satisfied

**Comment by gptshubham595** [comment]
in windows any solution.

I have install tensorflow==2.1
I have tf-gpu==2.2.0
I have gast==0.3.3
No Cuda

Also installed termcolor by pip install but on running it says no module installed:
