### ISSUE TITLE
thank you >:C

### ISSUE THREAD

**Issue by r3x07** [stormshadow07/HackTheWorld#7]
your script uninstalled my metasploit

**Comment by r3x07** [comment]
but it still didnt work my metasploit console cant see it

**Comment by stormshadow07** [comment]
@deadfishhackers Dude, Can you send me a video because this thing is rare. There is no Command in the script to Uninstall Metasploit. Next time add me using @stormshadow07 I did not get notification

**Comment by r3x07** [comment]
sorry it was all my OS. @stormshadow07 is this detectable?

**Comment by stormshadow07** [comment]
@deadfishhackers Its been a year almost and yeah this bypasses most of the good Antiviruses
