### ISSUE TITLE
i got big issue in 

### ISSUE THREAD

**Issue by dutchman11** [stormshadow07/HackTheWorld#9]
mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "./result/final_4444.exe". File not found.
DbgPrint says: mt exited with error: 0x0000001f - General failure.

**Comment by stormshadow07** [comment]
I tried it and it is Working Fine brother. It's probably from your end.

**Comment by 0000000O0Oo** [comment]
same issue over here help will be appreciated
